[theme]
primaryColor = "#FDD835"               # Amarillo pato, m치s suave
backgroundColor = "#FCF8E3"            # Beige claro, menos brillo que blanco puro
secondaryBackgroundColor = "#FFF9C4"   # Amarillo pastel (igual que el tuyo)
textColor = "#4E342E"                  # Marr칩n oscuro, mejor contraste y m치s c치lido
font = "sans serif"
